openapi: 3.0.3
info:
  title: Aggregation Service
  description: Aggregation Service
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:4000'
    description: Local Dev server
paths:
  /aggregation:
    get:
      summary: Returns aggregated result (of shipment products, track status and base price) for given orders and country codes
      operationId: aggregatedResult
      tags:
        - Aggregation Service
      parameters:
        - name: shipmentsOrderNumbers
          in: query
          schema:
            type: array
            items:
              type: integer
          description: Shipment Order Numbers
        - name: trackOrderNumbers
          in: query
          schema:
            type: array
            items:
              type: integer
          description: Track Order Numbers
        - name: pricingCountryCodes
          in: query
          schema:
            type: array
            items:
              type: string
          description: Pricing Country Codes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedResult'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: string
                example: 503 Unavailable

components:
  schemas:
    AggregatedResult:
      type: object
      properties:
        shipments:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        track:
          type: object
          additionalProperties:
            type: string
            enum:
              - UNKNOWN
              - NEW
              - IN_TRANSIT
              - COLLECTING
              - COLLECTED
              - DELIVERING
              - DELIVERED
        pricing:
          type: object
          additionalProperties:
            type: number


  
