openapi: 3.0.3
info:
  title: Track Service
  description: Track Service
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:4000'
    description: Local Dev server
  - url: 'http://backend-services:4000'
    description: Local Docker container URL
paths:
  /track-status:
    get:
      summary: Returns the tracking status of an order
      operationId: getTrackingStatus
      tags:
        - Track Service
      parameters:
        - name: orderNumber
          in: query
          schema:
            type: integer
            maxLength: 9
          description: Order Number
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                example: IN_TRANSIT, NEW, COLLECTING
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: string
                example: 503 Unavailable

  
